version: '3.8'

services:
  web:
    build: .
    container_name: click-counter-web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://clickuser:clickpass@db:5432/clickdb
      - PORT=5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16-alpine
    container_name: click-counter-db
    environment:
      - POSTGRES_USER=clickuser
      - POSTGRES_PASSWORD=clickpass
      - POSTGRES_DB=clickdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clickuser -d clickdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge

