apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: click-counter
  labels:
    app: click-counter
    component: web
data:
  PORT: "5000"
  POSTGRES_DB: "clickdb"
  POSTGRES_USER: "clickuser"

