apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: click-counter

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-init-configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: click-counter
  managed-by: kustomize

images:
  - name: ghcr.io/USERNAME/REPO
    newTag: latest

